updated code-scan.yml file

diff --git a/.github/workflows/code-scan.yml b/.github/workflows/code-scan.yml
--- a/.github/workflows/code-scan.yml
+++ b/.github/workflows/code-scan.yml
@@ -150,22 +150,56 @@ jobs:
     name: "Checkov"
     runs-on: ubuntu-latest
     needs: tfsec
+    defaults:
+      run:
+        shell: bash
     env:
       TF_IN_AUTOMATION: "true"
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5.0.1
 
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v3
+      # - name: Set up Python
+      #   uses: actions/setup-python@v6.1.0
+      #   with:
+      #     python-version: "3.13"
+
+      # - name: Install Checkov
+      #   run: pip install checkov
+
+      # - name: Run Checkov
+      #   run: |
+      #     checkov -d . --output json \
+      #       --download-external-modules True \
+      #       > checkov_results.json || true
+
+      - name: Checkov GitHub Action
+        id: checkov
+        uses: bridgecrewio/checkov-action@v12.3075.0
         with:
-          terraform_version: latest
+          # This will add both a CLI output to the console and create a results.sarif file
+          directory: .
+          framework: terraform
+          quiet: true
+          soft_fail: true
+          output_format: sarif
+          output_file_path: results.sarif
+          # output_format: cli,sarif
+          # output_file_path: console,checkov-scan-results.sarif
+          skip_check: CKV2_GHA_1
+        continue-on-error: true
+      - name: Upload SARIF file
+        uses:
+          github/codeql-action/upload-sarif@v4
 
-      - name: Terraform Init
-        run: terraform init -input=false
-
-      - name: Terraform Plan (json)
-        run: terraform plan -out=tfplan.bin && terraform show -json tfplan.bin > tfplan.json
+          # Results are generated only on a success or failure
+          # this is required since GitHub by default won't run the next step
+          # when the previous one has failed. Security checks that do not pass will 'fail'.
+          # An alternative is to add `continue-on-error: true` to the previous step
+          # Or 'soft_fail: true' to checkov.
+        if: success() || failure()
+        with:
+          sarif_file: results.sarif
 
       - name: Run Checkov on plan
         uses: bridgecrewio/checkov-action@v12
